apiVersion: v1
kind: Service
metadata:
  name: pomodoro-frontend
spec:
  selector:
    app: pomodoro-frontend
  ports:
    - port: 8080        # Service port
      targetPort: 80    # Container port (nginx)
  type: ClusterIP
